### PR TITLE
Split openedx-calc library out of edx-platform

### PR DESCRIPTION
**Pull request by stvstnfrd**

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@ormsbee @nasthagiri Here's the "new" package I mentioned yesterday..

Per F2F, I preserved the original git history for this package;
it is represented by `master` on this repo [1].

This PR into `master` represents the packaging requirements to update it to a standalone app,
including `travis-ci` and `coveralls` integration, as well as some general cleanup.

- [1] https://github.com/stvstnfrd/openedx-calc/commits/master

**Comment by stvstnfrd** [comment]
Note: Since this repo was created, `python-modernize` has been run against this code,
as well as a few other updates. These changes will be incorporated into this repo prior to change.

https://openedx.atlassian.net/browse/INCR-151

**Comment by nasthagiri** [comment]
Thanks @stvstnfrd.  Glad to see this moving forward.

**Review by feanil — APPROVED** [review]

**Comment by stvstnfrd** [comment]
Closing in favor of https://github.com/edx/openedx-calc/pull/1

**Pull request closed without merging**
